name: Python CI

on:
  push:
    branches: [ master ]
    paths:
      - 'python/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'python/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        cd python
        pip install .[test]
    - name: Run tests
      run: |
        cd python
        python -m pytest
